### ISSUE TITLE
figma font

### ISSUE THREAD

**Issue by 8PEI** [nitinrgupta/figma-better-font-picker#19]
hello everyone, 

I have  a hard time to see different fonts in my text. 
I just install a plugin but it's still look the same. I wonder if you have the same issue? [](url)

![image](https://user-images.githubusercontent.com/72937285/96159034-6cb9c600-0ed1-11eb-8407-e75d7fd45a41.png)

**Comment by yenargy** [comment]
@8PEI you need to open the plugin to view the fonts. Right-click on the canvas, go to plugin sections, and look for Better font picker and you'll be able to see the plugin with the font previews.
