### ISSUE TITLE
I installed the plug-in but am not seeing a difference

### ISSUE THREAD

**Issue by CelesteCote** [nitinrgupta/figma-better-font-picker#20]
Is the plugin meant to work with the in-browser version as well as the desktop app? I'm using the browser version (on a work laptop that limits program downloads) and am not seeing any difference in the font menu even after installing the plug-in. Did I miss a step?

(Also, thank you for creating this! The irony that a prototyping tool doesn't allow designers to preview fonts...)

**Comment by taymitnick** [comment]
I'm also having this issue! I'm using the app and restarted it after downloading and nothing has changed.

**Comment by cookiecat05** [comment]
@CelesteCote @taymitnick Hi! Have you tried activating the plugin? Open Figma's hamburger/file menu on the upper left, and under "Plugins" you should see the plugin "Better Font Picker". After clicking it you should see a new list of fonts pop up, separate from the standard Figma ones.

**Comment by yenargy** [comment]
@winnysomecookies thanks for the help in response. Closing this issue for now.
